[Bug] Fix createPostmanCollection method where a copy of openapiData is generated
PaloAltoNetworks/docusaurus-openapi-docs pull request #183
Opened 2022-07-31 13:23 UTC by johnnyswan

## Description

This PR introduces the following changes:

1. Fix `createPostmanCollection` method where a copy of `openapiData` is generated
2. Add `groupId` to `Tabs` component for Authentication section in generated `*.info.mdx` file

## Motivation and Context

1. The motivation is to fix the problem when some paths can have their own server object. For example:
```yaml
openapi: 3.0.3
info:
  title: Burger Example
  version: 1.0.0
  description: Sample description.
servers:
  - url: https://api.example.com/v1
paths:
  /user:
    get:
      servers:
        - url: https://users.example.com/v1
      responses:
        200:
          description: OK
  /flavors:
    get:
      responses:
        200:
          description: OK
```
The previous realization with `Object.assign` does not copy nested objects, and the next operation with deleting 'servers' attributes removes them into the parent object too.

2. Fix problem when changing of Authentication method in `*.info.mdx` file does not save user choice to storage and does not change security scheme all over the documentation

## How Has This Been Tested?

Environment: Local

Changes were tested by viewing specific API docs to ensure functionality for API docs were intact and ensuring that the app builds successfully upon each change.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have read the CONTRIBUTING document.
- [x] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2022-08-01 13:43 UTC, sserrata commented
Hi @johnnyswan, thanks for your contribution! The `cloneDeep` implementation looks good but it looks like we missed an opportunity to "tree shake" the `kebabCase` import. Can you refactor as follows?

Change this:

```
import { kebabCase, cloneDeep } from "lodash";
```

To this:

```
import { kebabCase } from "lodash/kebabCase";
import { cloneDeep } from "lodash/cloneDeep";
```

As for the `groupId` change for the authentication tabs, I was wondering what the expected behavior/use-case should be. Based on the change alone, I would only expect the tab choice to be persisted in `localStorage`. Is the idea to eventually support reading the tab choice from `localStorage` and using it somewhere else? I ask because sometimes the authentication tab choices are meant to be used in combination, like when multiple authentication headers are required for example - just something to keep in mind.

2022-08-01 18:28 UTC, johnnyswan commented
I plan to use `groupId` in `SecuritySchemes`-like component

2022-08-01 19:00 UTC, sserrata commented
Gotcha - definitely excited to see what you have in mind! 

In that case, I think it's best to leave the `groupId` change out of this PR with the intent to reintroduce it with the new SecuritySchemes-like component.

2022-08-01 19:19 UTC, sserrata requested changes
Remove `groupId` from `createAuthentication` until new SecurityScheme component is introduced. Thanks!

2022-08-01 19:48 UTC, sserrata approved these changes
🚀

2022-08-01 20:17 UTC, merged

2022-08-02 07:47 UTC, TarasMelnyk commented
Can you please say when will be the release of this fix? I have the same issue.

2022-08-02 12:06 UTC, sserrata commented
Hi @TarasMelnyk, we should have a new production release out later this week. If you need it sooner, you can always upgrade to a canary release, which auto publishes whenever we merge to main.

![image](https://user-images.githubusercontent.com/9343811/182370583-5ccb8d62-e764-4a37-b0d0-a089af8d7294.png)